### ISSUE TITLE
We need a clear example

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [nericode/nativescript-paypal-checkout#3]
This is not an issue but a marketing suggestion.

First of all thank you for your effort on creating this plugin.

Initially I was  very happy to see someone spent time and effort to provide us an easy way to integrate with paypal payments and braintree platform etc. but after half of day of work I don't succeed to make this working on my nativescript angular (7) app.

So for that, I strongly suggest to accompany your plugin with clear example(s), very well detailed, in how to integrate this plugin in different nativescript app otherwise all you effort it was for nothing. 

To be honest I don't have time to spent to understand what is behind this integration but I need the integration working on my app with a minimum effort.

For instance is absolutely not clear how to get the TOKEN (some print screen will help thought) .

I also need an implementation for TEST an another for PROD.

Is time to sell your plugin so please focus on the DETAILED example

Many thanks in advance

**Comment by nericode** [comment]
@ittrad-mobile-lab 


Sorry but this place is not for code suggestions, it asks you in the most careful way that if you found an error with version 6.X please add the error here.

The migration for version 7.X of NS will no longer be available from me, but if you have a PR it is welcome.
